// Deck runtime — `/_kit/deck.js`. Load as a module; it self-runs.
//
//   <link rel="stylesheet" href="/_kit/deck.css">
//   <script type="module" src="/_kit/deck.js"></script>
//
// Scaffold one with `bootstrap.ts <slug> --deck`. Structure it expects — all of
// it already the convention, none of it new:
//
//   #viewport > #deck > .stage > section.slide      slides, in document order
//                     > .segbar#segbar               progress bar (filled here)
//                     > .hint#hint                   fades on first keypress
//   .frag        inside a slide: reversible arrow-stepped build
//   .num[data-to] inside a slide: counts up on entry
//
// KEYED OFF #deck, NOT a class on <body>. That is deliberate: the poster kit
// briefly put `.poster` on <body> and collided with a page that already used
// `.poster` for its own element, silently scaling the whole card to 73.5%.
// Anything put on <body> shares a namespace with the page.
//
// DO NOT EDIT THIS FILE TO CHANGE ONE DECK. Every deck in every repo shares it.
// Regression gate: shoot every slide of every deck before and after any change
// here — `go(n, true)` is exposed on window precisely so tooling can drive
// slides deterministically instead of tabbing through fragments.

const deck = document.getElementById("deck");
if (deck) {
  // Scale from the canvas's own resolved size, so the design resolution lives in
  // exactly one place (--deck-w/--deck-h in the page's :root).
  const fit = () => {
    const c = getComputedStyle(deck);
    deck.style.setProperty(
      "--s",
      Math.min(innerWidth / parseFloat(c.width), innerHeight / parseFloat(c.height)),
    );
  };
  addEventListener("resize", fit);
  fit();

  const slides = [...document.querySelectorAll(".slide")];
  const segWrap = document.getElementById("segbar");
  let i = 0;

  const segs = [];
  if (segWrap) {
    slides.forEach((_, n) => {
      const b = document.createElement("b");
      b.onclick = (e) => { e.stopPropagation(); go(n); };
      segWrap.appendChild(b);
      segs.push(b);
    });
  }

  // count-up any .num[data-to] on slide entry
  function countUp(slide) {
    slide.querySelectorAll(".num[data-to]").forEach((el) => {
      const to = +el.dataset.to, suf = el.dataset.suffix || "", dur = 900, t0 = performance.now();
      (function tick(t) {
        const p = Math.min(1, (t - t0) / dur);
        el.textContent = Math.round(to * (1 - Math.pow(1 - p, 3))) + suf;
        if (p < 1) requestAnimationFrame(tick);
      })(t0);
    });
  }

  const setFrags = (slide, showAll) =>
    slide.querySelectorAll(".frag").forEach((f) => f.classList.toggle("in", showAll));

  function updateFragBar() {
    if (!segs.length) return;
    segs.forEach((s) => { s.classList.remove("split"); s.replaceChildren(); });
    const frags = [...slides[i].querySelectorAll(".frag")];
    if (!frags.length) return;
    segs[i].classList.add("split");
    frags.forEach((f) => {
      const t = document.createElement("i");
      if (f.classList.contains("in")) t.classList.add("lit");
      segs[i].appendChild(t);
    });
  }

  function go(n, showFrags) {
    n = Math.max(0, Math.min(slides.length - 1, n));
    const back = n < i;
    if (n === i && slides[i].classList.contains("active")) return;
    slides.forEach((s, k) => {
      s.classList.toggle("active", k === n);
      s.classList.toggle("past", k < n);
    });
    i = n;
    segs.forEach((d, k) => { d.classList.toggle("done", k <= n); d.classList.toggle("cur", k === n); });
    setFrags(slides[n], showFrags !== undefined ? showFrags : back);
    updateFragBar();
    if (slides[n].querySelector(".num[data-to]")) setTimeout(() => countUp(slides[n]), 340);
    // THE EXTENSION POINT. Decks that need per-slide behaviour of their own — a
    // page number, bars that grow on entry, drawers that close — hook this
    // instead of editing the runtime. Before it existed, those decks had fused
    // their code INTO go(), which is exactly why the machinery had drifted in
    // all five copies and could not be shared.
    //   addEventListener("deck:slide", e => { e.detail.index; e.detail.slide });
    dispatchEvent(new CustomEvent("deck:slide",
      { detail: { index: n, slide: slides[n], total: slides.length, back } }));
  }

  document.addEventListener("keydown", (e) => {
    const k = e.key;
    if (k === "ArrowRight" || k === "ArrowDown" || k === " " || k === "PageDown") {
      e.preventDefault();
      const next = [...slides[i].querySelectorAll(".frag")].find((f) => !f.classList.contains("in"));
      if (next) { next.classList.add("in"); updateFragBar(); } else go(i + 1, false);
      document.getElementById("hint")?.classList.add("hide");
    } else if (k === "ArrowLeft" || k === "ArrowUp" || k === "PageUp") {
      e.preventDefault();
      const shown = [...slides[i].querySelectorAll(".frag")].filter((f) => f.classList.contains("in"));
      if (shown.length) { shown[shown.length - 1].classList.remove("in"); updateFragBar(); }
      else go(i - 1, true);
    } else if (k === "Home") go(0);
    else if (k === "End") go(slides.length - 1);
    else if (k === "f" || k === "F") {
      if (!document.fullscreenElement) document.documentElement.requestFullscreen();
      else document.exitFullscreen();
    }
  });

  // Exposed for tooling (and for a deck's own content script, some of which
  // call go() to jump around). A module scope would otherwise hide it.
  window.go = go;
  window.__deckSlides = slides;

  window.focus();

  // Deep link: `…/#3` opens on slide 3 (1-based). Lifted out of one deck's own
  // content script during the migration — it is machinery, not content, and
  // promoting it hands the same feature to every other deck for free.
  const fromHash = parseInt(location.hash.slice(1), 10);
  go(Number.isFinite(fromHash) ? Math.max(1, Math.min(slides.length, fromHash)) - 1 : 0);
}
