// Deck runtime — `/_kit/deck.js`. Load as a module; it self-runs.
//
//   <link rel="stylesheet" href="/_kit/deck.css">
//   <script type="module" src="/_kit/deck.js"><\/script>   (escaped: this file gets pasted inline)
//
// Start one with `viz create <slug> --from deck`. Structure it expects — all of
// it already the convention, none of it new:
//
//   #viewport > #deck > .stage > section.slide      slides, in document order
//                     > .segbar#segbar               progress bar (filled here)
//                     > .hint#hint                   fades on first keypress
//   .frag        inside a slide: reversible arrow-stepped build
//   .num[data-to] inside a slide: counts up on entry
//   aside.notes  inside a slide: speaker notes (S opens the speaker view)
//
// RUNS ON reveal.js 5, pinned below and loaded from the CDN like every other
// third-party import in viz (inline.ts leaves https:// imports external, so a
// published single-file deck loads it the same way). Reveal supplies navigation,
// fragments, hash deep links, overview (O), speaker view (S), black-out (B) and
// `?print-pdf`. This file maps the kit's contract onto it: #deck is reveal's root
// and .stage its `.slides`; `.frag` becomes a reveal fragment and mirrors
// `.visible` as `.in`; the current slide gets `.active`. The decks' own CSS keys
// off those kit names, so no deck had to change for the move.
//
// reveal.css is deliberately NOT loaded. It styles `.reveal`, `.slides`,
// `section`, `.fragment` and more at 0-2-1 specificity — it would restyle every
// slide of every deck. deck.css carries the few rules reveal's JS actually needs
// (overview, print, black-out). Layout is ours too (disableLayout): #deck keeps
// scaling itself, so everything outside .stage (backgrounds, masthead, segbar)
// scales with it.
//
// KEYED OFF #deck, NOT a class on <body>. That is deliberate: the poster kit
// briefly put `.poster` on <body> and collided with a page that already used
// `.poster` for its own element, silently scaling the whole card to 73.5%.
// Anything put on <body> shares a namespace with the page.
//
// DO NOT EDIT THIS FILE TO CHANGE ONE DECK. Every deck in every repo shares it.
// Regression gate: shoot every slide of every deck before and after any change
// here — `go(n, true)` is exposed on window precisely so tooling can drive
// slides deterministically instead of tabbing through fragments.

import Reveal from "https://cdn.jsdelivr.net/npm/reveal.js@5.2.1/dist/reveal.esm.js";
import RevealNotes from "https://cdn.jsdelivr.net/npm/reveal.js@5.2.1/plugin/notes/notes.esm.js";

const deck = document.getElementById("deck");
if (deck) {
  // Scale from the canvas's own resolved size, so the design resolution lives in
  // exactly one place (--deck-w/--deck-h in the page's :root).
  const c = getComputedStyle(deck);
  const W = parseFloat(c.width), H = parseFloat(c.height);
  const fit = () => deck.style.setProperty("--s", Math.min(innerWidth / W, innerHeight / H));
  // In a window smaller than the canvas, #viewport's grid track grows to the
  // unscaled canvas and starts at the left edge, so the scaled deck lands
  // off-centre. The speaker view's small preview iframes always hit this.
  document.getElementById("viewport")?.style.setProperty("place-content", "center");
  addEventListener("resize", fit);
  fit();

  const slides = [...document.querySelectorAll(".slide")];
  const frags = [...deck.querySelectorAll(".frag")];
  const segWrap = document.getElementById("segbar");
  deck.classList.add("reveal");
  document.querySelector("#deck > .stage")?.classList.add("slides");
  frags.forEach((f) => f.classList.add("fragment"));

  // Deep link: the kit's old `…/#3` (1-based) becomes reveal's `#/3`.
  if (/^#\d+$/.test(location.hash)) history.replaceState(null, "", "#/" + location.hash.slice(1));

  const R = new Reveal(deck, {
    width: W, height: H, margin: 0, disableLayout: true, center: false,
    controls: false, progress: false, help: false, jumpToSlide: false,
    hash: true, hashOneBasedIndex: true, respondToHashChanges: true,
    transition: "none", backgroundTransition: "none", hideInactiveCursor: false,
    display: "",               // leave `display` to the deck's own .slide rule
    viewDistance: 1e9,         // never display:none a slide — the kit cross-fades them
    pdfSeparateFragments: false, pdfMaxPagesPerSlide: 1,   // one PDF page per slide
    keyboard: {
      70: () => document.fullscreenElement ? document.exitFullscreen() : document.documentElement.requestFullscreen(),
      27: () => R.isOverview() && R.toggleOverview(false),  // Esc belongs to the deck unless in overview
    },
    plugins: [RevealNotes],
  });

  const segs = [];
  if (segWrap) {
    slides.forEach((_, n) => {
      const b = document.createElement("b");
      b.onclick = (e) => { e.stopPropagation(); go(n); };
      segWrap.appendChild(b);
      segs.push(b);
    });
  }

  // count-up any .num[data-to] on slide entry
  function countUp(slide) {
    slide.querySelectorAll(".num[data-to]").forEach((el) => {
      const to = +el.dataset.to, suf = el.dataset.suffix || "", dur = 900, t0 = performance.now();
      (function tick(t) {
        const p = Math.min(1, (t - t0) / dur);
        el.textContent = Math.round(to * (1 - Math.pow(1 - p, 3))) + suf;
        if (p < 1) requestAnimationFrame(tick);
      })(t0);
    });
  }

  let i = -1;
  // Reveal owns state; this mirrors it onto the kit's classes and the segbar.
  // In overview and print every slide is `.active`, so each deck's own entrance
  // rules (keyed on .slide.active) show every slide fully built.
  function sync() {
    const all = R.isOverview() || R.isPrintView();
    slides.forEach((s, k) => s.classList.toggle("active", all || k === i));
    frags.forEach((f) => f.classList.toggle("in", all || f.classList.contains("visible")));
    if (!segs.length) return;
    segs.forEach((d, k) => {
      d.classList.toggle("done", k <= i); d.classList.toggle("cur", k === i);
      d.classList.remove("split"); d.replaceChildren();
    });
    const own = [...slides[i].querySelectorAll(".frag")];
    if (!own.length) return;
    segs[i].classList.add("split");
    own.forEach((f) => {
      const t = document.createElement("i");
      if (f.classList.contains("in")) t.classList.add("lit");
      segs[i].appendChild(t);
    });
  }

  function entered(n) {
    const back = n < i;
    i = n;
    sync();
    if (slides[n].querySelector(".num[data-to]")) setTimeout(() => countUp(slides[n]), 340);
    // THE EXTENSION POINT. Decks that need per-slide behaviour of their own — a
    // page number, bars that grow on entry, drawers that close — hook this
    // instead of editing the runtime. Before it existed, those decks had fused
    // their code INTO go(), which is exactly why the machinery had drifted in
    // all five copies and could not be shared.
    //   addEventListener("deck:slide", e => { e.detail.index; e.detail.slide });
    dispatchEvent(new CustomEvent("deck:slide",
      { detail: { index: n, slide: slides[n], total: slides.length, back } }));
  }

  // go(n) keeps reveal's rule (arriving backwards shows every fragment);
  // go(n, true|false) forces all fragments shown or hidden.
  function go(n, showFrags) {
    n = Math.max(0, Math.min(slides.length - 1, n));
    R.slide(n, 0, showFrags === undefined ? undefined : showFrags ? Infinity : -1);
  }

  R.on("slidechanged", (e) => entered(e.indexh));
  R.on("fragmentshown", sync);
  R.on("fragmenthidden", sync);
  R.on("overviewshown", sync);
  R.on("overviewhidden", sync);
  R.on("pdf-ready", () => {
    sync();
    document.querySelectorAll(".num[data-to]").forEach((el) => { el.textContent = el.dataset.to + (el.dataset.suffix || ""); });
  });
  R.on("ready", (e) => {
    // Reveal copies each slide's classes onto its (hidden) background element;
    // left there, every `.slide` query and rule would see the deck twice.
    deck.querySelectorAll(".slide-background").forEach((b) => b.classList.remove("slide"));
    entered(e.indexh);
  });
  document.addEventListener("keydown", () => document.getElementById("hint")?.classList.add("hide"));

  // After every module script has run (they all precede DOMContentLoaded), so a
  // deck's own script that walks `.slide` sees the slides, not reveal's copies.
  // `load` and the readyState check cover a deck.js that arrives late (a sealed
  // page is document.write()n after it decrypts).
  let started = false;
  const start = () => { if (!started) { started = true; R.initialize(); } };
  if (document.readyState === "complete") start();
  else { addEventListener("DOMContentLoaded", start); addEventListener("load", start); }

  // Exposed for tooling (and for a deck's own content script, some of which
  // call go() to jump around). A module scope would otherwise hide it.
  window.go = go;
  window.__deckSlides = slides;
  window.__deckReveal = R;

  window.focus();
}
