// The exchange runtime — `/_kit/exchange.js`.
//
// An EXCHANGE is a diagram of something being presented, passed or proven
// between parties: actors in phase bands, declared wires between them, a
// labelled packet animating along a wire, and a stepped narration. Scaffold one
// with `bootstrap.ts <slug> --exchange`; the shape of the data is EXCHANGE.md.
//
// It is deliberately NOT a UML sequence diagram. There are no lifelines: the
// vertical axis is PHASE, not time, and an actor is repeated in each band it
// takes part in. That is the trade — you give up the continuous lifeline and
// get to say how OFTEN each band happens ("once" / "per token" / "per request"),
// which a sequence diagram cannot express.
//
// It owns the EXPERIENCE: zones, lanes, boxes, wires, animated packets that ride
// in and park, per-phase result panels, the stepper, autoscroll. It knows nothing
// about any particular protocol -- that lives in a variant's content.js.
//
// ─────────────────────────────────────────────────────────────────────────────
// DO NOT EDIT THIS FILE TO CHANGE ONE VARIANT. Every exchange in every repo
// shares it, so an edit here changes all of them. Everything a variant needs to
// differ is already data in its content.js -- see EXCHANGE.md. If you genuinely
// cannot express something as data, stop and say so rather than editing this.
//
// Regression gate: `bun check-exchange.mjs <viz-dir>` must stay green on every
// exchange in the corpus after any change here.
// ─────────────────────────────────────────────────────────────────────────────

const SVGNS = 'http://www.w3.org/2000/svg';
const el = (t, c, h) => { const d = document.createElement(t); if (c) d.className = c;
                          if (h != null) d.innerHTML = h; return d; };

export function mount(exchange) {
  const STEPS = exchange.steps;
  const STAGE_W = (exchange.stage && exchange.stage.w) || 1780;
  const STAGE_H = (exchange.stage && exchange.stage.h) || 1630;

  if (exchange.theme) {
    const vars = Object.entries(exchange.theme).map(([k, v]) => `--${k}:${v}`).join(';');
    document.head.append(el('style', null, `:root{${vars}}`));
  }

  // ---- shell -------------------------------------------------------------
  const topbar = el('div', 'topbar', `<h1>${exchange.title}</h1>
    <div class="sub">${exchange.subtitle || ''}</div><div class="spacer"></div>
    <div class="controls">
      <button id="restart">⟲ Restart</button><button id="prev">‹ Step</button>
      <button id="play" class="primary">▶ Play</button><button id="next">Step ›</button>
    </div>`);
  const wrap = el('div', 'stagewrap');
  const stage = el('div', 'stage'); stage.id = 'stage';
  stage.style.width = STAGE_W + 'px'; stage.style.height = STAGE_H + 'px';
  const svg = document.createElementNS(SVGNS, 'svg'); svg.id = 'wires';
  const pktLayer = document.createElementNS(SVGNS, 'svg'); pktLayer.id = 'pkts';
  // Both the ATTRIBUTE and the inline STYLE, and the style is the one that matters:
  // engine.css pins #wires/#pkts to the 1780x1630 default, and a CSS declaration
  // beats a presentation attribute — so on a larger stage these layers stayed
  // 1780 wide and only kept working because they are overflow:visible. Verified
  // 2026-08-06 on the 1900px variant, where clientWidth read 1780.
  for (const s of [svg, pktLayer]) {
    s.setAttribute('width', STAGE_W); s.setAttribute('height', STAGE_H);
    s.style.width = STAGE_W + 'px'; s.style.height = STAGE_H + 'px';
  }
  stage.append(svg, pktLayer); wrap.append(stage);
  const narr = el('div', 'narr', `<div class="narrinner">
      <div class="stepno" id="stepno"></div>
      <div class="narrtext"><div class="nt" id="ntitle"></div><div class="track" id="track"></div></div>
    </div>`);
  document.body.append(topbar, wrap, narr);
  const $ = s => document.querySelector(s);

  // ---- geometry ----------------------------------------------------------
  const N = exchange.nodes, B = exchange.boxes || {};
  const G = id => N[id] || B[id];
  const cx = n => n.x + n.w / 2, cy = n => n.y + n.h / 2;

  for (const z of exchange.zones || []) {
    const d = el('div', 'zone ' + (z.cls || ''));
    Object.assign(d.style, { left: z.x + 'px', top: z.y + 'px', width: z.w + 'px', height: z.h + 'px' });
    d.append(el('div', 'ztitle', z.title), el('div', 'zsub', z.sub || ''));
    stage.append(d);
  }
  for (const f of exchange.firewalls || []) {
    const d = el('div', 'fw');
    Object.assign(d.style, { left: f.x + 'px', top: f.y + 'px', height: f.h + 'px' });
    stage.append(d);
    const l = el('div', 'fwlabel', f.label);
    Object.assign(l.style, { left: (f.x - 15) + 'px', top: (f.y + (f.labelAt || 520)) + 'px' });
    stage.append(l);
  }
  for (const L of exchange.lanes) {
    const d = el('div', 'lane'); d.id = 'lane' + L.id;
    Object.assign(d.style, { left: '16px', top: L.y + 'px', width: (STAGE_W - 32) + 'px', height: L.h + 'px' });
    const t = el('div', 'lanetag', `${L.tag}<b>${L.name}</b>`);
    Object.assign(t.style, { left: (L.tagX || 344) + 'px', top: '-44px' });
    d.append(t); stage.append(d);
  }

  const nodeEls = {};
  for (const [id, n] of Object.entries(N)) {
    const d = el('div', 'node ' + (n.cls || ''));
    d.dataset.vizId = 'node-' + id; d.dataset.label = n.name;
    Object.assign(d.style, { left: n.x + 'px', top: n.y + 'px', width: n.w + 'px', height: n.h + 'px' });
    d.innerHTML = (n.tag ? `<div class="ntag">${n.tag}</div>` : '')
      + `<div class="nname">${n.name}</div>`
      + (n.role ? `<div class="nrole">${n.role}</div>` : '')
      + (n.spec ? `<div class="specrole">${n.spec}</div>` : '');
    if (n.spec) d.style.paddingBottom = '26px';
    stage.append(d); nodeEls[id] = d;
  }

  for (const p of exchange.panels || []) {
    const d = el('div', 'panelbox ' + (p.cls || '')); d.id = p.id;
    d.dataset.vizId = p.id; d.dataset.label = p.title;
    Object.assign(d.style, { left: p.x + 'px', top: p.y + 'px', width: p.w + 'px' });
    d.innerHTML = `<h5>${p.title}</h5><div class="body ${p.bodyCls || ''}">${p.body || ''}</div>`;
    stage.append(d);
  }
  for (const b of exchange.labels || []) {
    const d = el('div', 'handlabel', b.text); d.id = b.id; d.dataset.vizId = b.id;
    Object.assign(d.style, { left: b.x + 'px', top: b.y + 'px' });
    stage.append(d);
  }

  // ---- wires -------------------------------------------------------------
  // Every endpoint is derived from node/box geometry, never typed as a literal,
  // so moving a box can never strand its arrows.
  function pathFor(a, b, o) {
    const A = G(a), B_ = G(b);
    if (o.up) { const x1 = cx(A), y1 = A.y, x2 = cx(B_), y2 = B_.y + B_.h;
      return `M ${x1} ${y1} C ${x1} ${y1 - 90}, ${x2} ${y2 + 90}, ${x2} ${y2}`; }
    if (o.dip) { const x1 = cx(A), y1 = A.y + A.h, x2 = B_.x, y2 = cy(B_);
      return `M ${x1} ${y1} C ${x1} ${y1 + 70}, ${x2 - 200} ${y2 + 80}, ${x2} ${y2}`; }
    if (o.back) { const x1 = cx(A), y1 = A.y + A.h, ry = cy(B_), x2 = B_.x + B_.w;
      return `M ${x1} ${y1} C ${x1} ${y1 + 60}, ${x1 - 200} ${ry}, ${x1 - 300} ${ry} L ${x2} ${ry}`; }
    if (o.hand) { const x1 = cx(A), y1 = A.y + A.h, x2 = cx(B_), y2 = B_.y;
      return `M ${x1} ${y1} L ${x2} ${y2}`; }
    const x1 = A.x + A.w, y1 = cy(A), x2 = B_.x, y2 = cy(B_), m = (x1 + x2) / 2;
    return `M ${x1} ${y1} C ${m} ${y1}, ${m} ${y2}, ${x2} ${y2}`;
  }

  const defs = document.createElementNS(SVGNS, 'defs');
  defs.innerHTML = ['#54688c', 'var(--accent)', 'var(--warn)', '#3f7f66', 'var(--good)'].map((c, i) =>
    `<marker id="ah${i}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="4.2" markerHeight="4.2"
      orient="auto-start-reverse"><path d="M0,1.4 L10,5 L0,8.6 z" fill="${c}"/></marker>`).join('');
  svg.append(defs);

  const wirePaths = {};
  for (const [a, b, o = {}] of exchange.wires) {
    const p = document.createElementNS(SVGNS, 'path');
    p.setAttribute('d', pathFor(a, b, o));
    // `o.cls` is a pass-through for variant-local wire styling, added 2026-08-06.
    // Purely additive: a wire without it renders exactly as before, so no existing
    // variant changes. It exists because shape opts (up/dip/back/hand) are the only
    // thing that reached the class list, and a variant had no way to say "this wire
    // is different in KIND" — e.g. proposed-vs-existing — as opposed to different in
    // route. Style it in the variant's index.html, never here.
    p.setAttribute('class', 'wire' + ((o.up || o.dip) ? ' dash' : '') + (o.back ? ' back' : '') + (o.hand ? ' hand' : '')
      + (o.cls ? ' ' + o.cls : ''));
    p.setAttribute('marker-end', 'url(#' + (o.back ? 'ah3' : o.hand ? 'ah4' : 'ah0') + ')');
    svg.append(p); wirePaths[a + '>' + b] = p;
  }

  // ---- optional travelling browser --------------------------------------
  let browser = null;
  if (exchange.browser) {
    browser = el('div', 'browser');
    browser.dataset.vizId = 'browser'; browser.dataset.label = 'browser';
    browser.innerHTML = `<div class="bchrome"><span class="bdot"></span><span class="bdot"></span>
      <span class="bdot"></span><span class="burl"><span class="lock">🔒</span>
      <span id="burl"></span></span></div><div class="bbody" id="bbody"></div>`;
    stage.append(browser);
  }
  function setBrowser(b) {
    if (!browser) return;
    const n = N[b.at];
    browser.style.left = (n.x + n.w / 2 - 135) + 'px';
    browser.style.top = (n.y + n.h + 30) + 'px';
    $('#burl').textContent = b.url; $('#bbody').innerHTML = b.body;
  }

  // ---- packets -----------------------------------------------------------
  // A packet rides in to the MIDPOINT of its wire and waits, so its label stays
  // readable while the step is on screen; leaving sends it the rest of the way.
  // Tracked as a list: stepping faster than the animation used to strand a chip
  // on screen for every skipped step.
  let live = [];
  const place = (g, path, rev, w, f) => {
    const pt = path.getPointAtLength((rev ? 1 - f : f) * path.getTotalLength());
    g.setAttribute('transform', `translate(${pt.x - w / 2},${pt.y - 11})`);
  };
  function sendOut(it) {
    const { g, path, reverse, w } = it, dur = 560, t0 = performance.now();
    (function frame(now) {
      const k = Math.min(1, (now - t0) / dur), e = 1 - Math.pow(1 - k, 3);
      place(g, path, reverse, w, 0.5 + 0.5 * e); g.style.opacity = String(1 - e);
      if (k < 1) requestAnimationFrame(frame); else g.remove();
    })(t0);
  }
  function clearLive() {
    for (const it of live) {
      it.path.classList.remove('hot', 'hotback');
      // A labelless packet registers ONLY so its wire gets un-lit here — see the
      // note in flyPacket. There is no <g> to fly out or remove.
      if (!it.g) continue;
      if (it.parked) sendOut(it); else { it.killed = true; it.g.remove(); }
    }
    live = [];
  }
  // NOTE: this does NOT clear previous packets — render() does that once, so a
  // step can fly several packets at the same time (see `also` below). Calling it
  // directly without clearing first will stack packets, which is the point.
  function flyPacket(from, to, label, ret, green) {
    const fwd = wirePaths[from + '>' + to], rev = wirePaths[to + '>' + from];
    const path = fwd || rev, reverse = !fwd && !!rev;
    if (!path) return;
    path.classList.add(green ? 'hotback' : 'hot');
    // A step may light a wire without flying a pill along it (`pkt: ''`), which is
    // what a hand-off between one phase's result and the next phase's client wants:
    // the wire is the whole message, so a label on it would just be furniture.
    //
    // IT STILL HAS TO BE REGISTERED. This used to `return` here, before the push
    // below — so the wire got `hot` and nothing ever took it off again, because
    // clearLive() only walks `live`. The wire stayed accent-blue for the rest of
    // the session, on every subsequent step, and a page whose palette means
    // something by blue was quietly telling the reader the wrong thing. Found
    // 2026-08-31 in member-api-poc-network-story, where the two hand-off wires
    // turned blue at step 10 and never went back; five pages in two repos use
    // `pkt: ''` and all of them had it.
    if (!label) { live.push({ path }); return; }
    const g = document.createElementNS(SVGNS, 'g');
    const w = Math.max(44, label.length * 6.4 + 16);
    const r = document.createElementNS(SVGNS, 'rect');
    r.setAttribute('width', w); r.setAttribute('height', 21); r.setAttribute('rx', 10.5);
    r.setAttribute('class', 'pkt' + (ret ? ' ret' : ''));
    const t = document.createElementNS(SVGNS, 'text');
    t.setAttribute('class', 'pktlabel'); t.setAttribute('text-anchor', 'middle');
    t.setAttribute('dy', '14.5'); t.setAttribute('x', w / 2); t.textContent = label;
    g.append(r, t); pktLayer.append(g); place(g, path, reverse, w, 0);
    const it = { g, path, reverse, w, parked: false, killed: false };
    live.push(it);
    const dur = 900, t0 = performance.now();
    (function frame(now) {
      if (it.killed) return;
      const k = Math.min(1, (now - t0) / dur);
      const e = k < .5 ? 2 * k * k : 1 - Math.pow(-2 * k + 2, 2) / 2;
      place(g, path, reverse, w, e * 0.5);
      if (k < 1) requestAnimationFrame(frame); else it.parked = true;
    })(t0);
  }

  // ---- playback ----------------------------------------------------------
  let i = 0, playing = false, timer = null, K = 1;
  const track = $('#track');
  STEPS.forEach((_, k) => { const t = el('div', 'tick'); t.onclick = () => { stop(); go(k); }; track.append(t); });

  function render() {
    const s = STEPS[i];
    $('#stepno').innerHTML = (i + 1) + '<small>of ' + STEPS.length + '</small>';
    $('#ntitle').textContent = s.t;
    [...track.children].forEach((t, k) => t.className = 'tick' + (k < i ? ' done' : k === i ? ' now' : ''));
    exchange.lanes.forEach(L => document.getElementById('lane' + L.id).classList.toggle('active', L.id === s.p));

    Object.values(nodeEls).forEach(e => e.classList.remove('lit'));
    const lit = s.lit || [
      ...(s.from && N[s.from] && N[s.to] ? [s.from, s.to] : s.from && N[s.from] ? [s.from] : []),
      // whatever a parallel packet flies into lights up too, otherwise the log
      // hop animates into a box that still looks asleep
      ...(s.also || []).flatMap(a => [a.from, a.to]).filter(id => N[id]),
    ];
    lit.forEach(id => nodeEls[id] && nodeEls[id].classList.add('lit'));

    if (s.browser) setBrowser(s.browser);
    if (browser) browser.style.opacity = (exchange.browserPhase || 1) === s.p ? '1' : '.3';
    // a step fills panels by id -- the engine never knows what any of them mean
    for (const [id, html] of Object.entries(s.set || {})) {
      const t = document.querySelector('#' + id + ' .body'); if (t) t.innerHTML = html;
    }
    // Clear once, here, then fly every packet this step wants. `s.also` is a list
    // of {from,to,pkt,ret} that animate SIMULTANEOUSLY with the main one — for
    // showing that a hop and its side effect (an audit log, a mirror write) happen
    // together rather than as separate steps later on. Added 2026-08-06.
    clearLive();
    if (s.from) flyPacket(s.from, s.to, s.pkt || '', s.ret, s.back || s.hand);
    for (const a of s.also || []) flyPacket(a.from, a.to, a.pkt || '', a.ret, a.green);

    // keep whatever the step is about roughly centred -- set autoscroll:false on a
    // exchange whose stage fits on screen, where the re-centring only reads as jumping
    if (exchange.autoscroll !== false) {
      const a = s.from && G(s.from), b = s.to && G(s.to);
      const anchor = a && b ? (cy(a) + cy(b)) / 2 : a ? cy(a) : (exchange.lanes.find(l => l.id === s.p).y + 160);
      const top = stage.getBoundingClientRect().top + scrollY;
      scrollTo({ top: Math.max(0, top + anchor * K - (innerHeight - 96) / 2), behavior: 'smooth' });
    }
    history.replaceState(null, '', '#step=' + i);
  }
  function go(k) { i = Math.max(0, Math.min(STEPS.length - 1, k)); render(); }
  function next() { if (i < STEPS.length - 1) { go(i + 1); return true; } return false; }
  function play() { playing = true; $('#play').textContent = '❚❚ Pause'; clearInterval(timer);
    timer = setInterval(() => { if (!next()) stop(); }, exchange.stepMs || 2400); }
  function stop() { playing = false; $('#play').textContent = '▶ Play'; clearInterval(timer); }

  $('#play').onclick = () => playing ? stop() : play();
  $('#next').onclick = () => { stop(); next(); };
  $('#prev').onclick = () => { stop(); go(i - 1); };
  // a reload is a free, always-correct reset -- no teardown code to keep in sync
  $('#restart').onclick = () => { location.hash = 'step=0'; location.reload(); };
  addEventListener('keydown', e => {
    if (e.key === 'ArrowRight') { stop(); next(); }
    if (e.key === 'ArrowLeft') { stop(); go(i - 1); }
    if (e.key === ' ') { e.preventDefault(); playing ? stop() : play(); }
  });

  function fit() {
    const k = K = Math.min(1, (innerWidth - 40) / STAGE_W);
    stage.style.transform = 'scale(' + k + ')';
    // scale() shrinks the stage visually but leaves its layout box full size
    stage.style.marginBottom = (-STAGE_H * (1 - k)) + 'px';
    stage.style.marginRight = (-STAGE_W * (1 - k)) + 'px';
  }
  addEventListener('resize', fit); fit();

  if (exchange.browser) setBrowser(exchange.browser);
  go(parseInt(new URLSearchParams(location.hash.slice(1)).get('step') || '0', 10) || 0);
}
