// lib/create/fork.ts — `--from`: copying an existing viz as the starting point.
//
// A fork ALWAYS resets to local/unlisted — posture is a trust decision and is never
// inherited — and drops the source's comments, og.auto.png and recordings.
//
// Extracted from bootstrap.ts.

import path from "node:path";
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync, cpSync } from "node:fs";
import { die } from "../../cli.ts";

// ---- --from: fork an existing viz ----

// Minimal meta upsert. Deliberately NOT imported from manage.ts: that would drag in
// build.ts (1700 lines) on every bootstrap just to rewrite three tags.
export function setMeta(html: string, name: string, content: string): string {
  const esc = content.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
  const re = new RegExp(`<meta\\s+name=["']${name}["'][^>]*>`, "i");
  const tag = `<meta name="${name}" content="${esc}">`;
  if (re.test(html)) return html.replace(re, tag);
  return html.replace(/<\/head>/i, `${tag}\n</head>`); // no existing tag → add one
}

// Files that belong to the SOURCE viz's identity or are regenerated artifacts —
// never inherited by a fork.
export const FORK_SKIP = new Set([
  "comments.json", // review scratch, tied to the original's elements
  "og.auto.png", // regenerated by verify.ts --og
  ".mirror.json", // marks a mirrored-in copy; a fork is not a mirror
  "recordings.json", // the source's captured API tape, possibly with secrets
]);

// Copy a viz dir, then RE-STAMP the copy's identity. The posture reset is the
// load-bearing part: a fork must never inherit `public`. ADR 0006 makes posture the
// one field that never crosses a boundary by inheritance, because access posture is
// a trust decision — the same logic applies to a copy. You opt back in deliberately.
export function forkFrom(srcDir: string, destDir: string, newSlug: string): void {
  if (!existsSync(path.join(srcDir, "index.html"))) {
    die(`ERROR: --from ${srcDir} has no index.html — that's not a viz.`);
  }
  if (existsSync(path.join(srcDir, ".mirror.json"))) {
    die(`ERROR: --from ${srcDir} is a mirrored-in copy, not an origin. Fork the origin instead.`);
  }
  cpSync(srcDir, destDir, {
    recursive: true,
    filter: (s) => {
      const b = path.basename(s);
      return !FORK_SKIP.has(b) && b !== ".git" && b !== "node_modules";
    },
  });
  const idx = path.join(destDir, "index.html");
  let html = readFileSync(idx, "utf8");
  html = setMeta(html, "viz:posture", "local"); // NEVER inherit public/private
  html = setMeta(html, "viz:listed", "unlisted");
  html = setMeta(html, "viz:title", newSlug);
  html = setMeta(html, "viz:description", "");
  writeFileSync(idx, html);
}
