// lib/render/narration.ts — narration.json → timed audio clips, warnings, and a muxed mp4.
//
// The script lives in the viz (narration.json + audio/), so it is content: committed,
// edited by the agent. What it compiles to — Kokoro clips and .tts/manifest.json — is build
// output: gitignored, regenerated by hash, bundled only by publish. The browser (kit
// narrate()) and the render read the same manifest, so what you hear while stepping the
// page is what ends up in the video.
//
// Voices: Kokoro (VIZ_KOKORO_URL moves it) and local Qwen3 clones through mlx-audio's server —
// each configured in voices.json (reference/timeline.md).

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";

const KOKORO = process.env.VIZ_KOKORO_URL ?? "http://127.0.0.1:8880";
export const TTS_DIR = ".tts";
export const NARRATION_FILE = "narration.json";

export type Cue = {
  /** "chapter:N" (a chapter's n), "beat:N" (1-based position in beats[]), or seconds. */
  at: string | number;
  say?: string;
  /** A file under the viz dir, e.g. "audio/whoosh.mp3". */
  audio?: string;
  voice?: string;
  speed?: number;
  /** dB, e.g. -18 to sit music under speech. */
  gain?: number;
  /** Transcribe this audio file (mlx_whisper) into captions — for a real voiceover, not music. */
  caption?: boolean;
};
type VoiceChoice = { id: string; label?: string };
export type Narration = { voice?: string; speed?: number; voices?: VoiceChoice[]; cues: Cue[] };
export type Shape = {
  total: number;
  chapters?: { n: number; t0: number; dur: number }[];
  beats?: { t0: number; dur: number }[];
};

/** One cue, placed on the timeline. `src` is relative to the viz dir — the manifest's URL. */
export type Placed = {
  at: Cue["at"];
  t: number;
  dur: number;
  slotDur?: number;
  src: string;
  gain: number;
  text?: string;
  caption?: boolean;
  words?: Word[];
};
export type Track = { id: string; label: string; cues: Placed[] };
export type Plan = { cues: Placed[]; tracks: Track[]; warnings: string[] };
type VoiceProfile = {
  id: string;
  label?: string;
  engine: "kokoro" | "qwen3";
  voice?: string;
  speed?: number;
  python?: string;
  model?: string;
  url?: string;
  referenceWav?: string;
  transcript?: string;
};

/** One property of a parsed-JSON value, still `unknown`: everything read from a file is checked before it is trusted. */
const field = (v: unknown, k: string): unknown =>
  typeof v === "object" && v !== null ? Reflect.get(v, k) : undefined;
const isString = (v: unknown): v is string => typeof v === "string";
const hasNums = (v: unknown, ...keys: string[]): boolean =>
  keys.every((k) => typeof field(v, k) === "number");
const isVoiceProfile = (v: unknown): v is VoiceProfile =>
  isString(field(v, "id")) && (field(v, "engine") === "kokoro" || field(v, "engine") === "qwen3");
const isNarration = (v: unknown): v is Narration => Array.isArray(field(v, "cues"));
const isWord = (v: unknown): v is Word =>
  Array.isArray(v) &&
  v.length === 3 &&
  typeof v[0] === "string" &&
  typeof v[1] === "number" &&
  typeof v[2] === "number";
const isCaption = (v: unknown): v is Caption =>
  typeof field(v, "start") === "number" &&
  typeof field(v, "end") === "number" &&
  isString(field(v, "text"));

function voiceConfig(): { defaults: string[]; profiles: VoiceProfile[] } {
  const file =
    process.env.VIZ_TTS_CONFIG ?? path.join(process.env.HOME ?? "", ".config/viz/voices.json");
  if (!existsSync(file)) return { defaults: [], profiles: [] };
  const c: unknown = JSON.parse(readFileSync(file, "utf8"));
  const defaults = field(c, "defaults");
  const profiles = field(c, "profiles");
  return {
    defaults: Array.isArray(defaults) ? defaults.filter(isString) : [],
    profiles: Array.isArray(profiles) ? profiles.filter(isVoiceProfile) : [],
  };
}

export function readNarration(vizDir: string): Narration | null {
  const f = path.join(vizDir, NARRATION_FILE);
  if (!existsSync(f)) return null;
  const n: unknown = JSON.parse(readFileSync(f, "utf8"));
  if (!isNarration(n)) throw new Error(`${f}: "cues" must be an array`);
  return n;
}

export async function probeDuration(file: string): Promise<number> {
  const p = Bun.spawn(
    ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", file],
    { stdout: "pipe" },
  );
  const d = Number((await new Response(p.stdout).text()).trim());
  if (!(d > 0)) throw new Error(`could not read the duration of ${file}`);
  return d;
}

/** Where a cue starts, and how long it has before the thing it is anchored to ends. */
/** A cue's file, resolved — null if it points outside the viz (publish would inline it). */
export function insideViz(vizDir: string, rel: string): string | null {
  const abs = path.resolve(vizDir, rel);
  const r = path.relative(vizDir, abs);
  return r && !r.startsWith("..") && !path.isAbsolute(r) ? abs : null;
}

function place(at: Cue["at"], shape: Shape): { t: number; slot: number } | string {
  if (typeof at === "number") {
    if (!(at >= 0 && at < shape.total)) return `cue at ${at}: outside the film (0–${shape.total}s)`;
    return { t: at, slot: shape.total - at };
  }
  const m = /^(chapter|beat):(\d+)$/u.exec(at);
  if (!m) return `cue at "${at}": expected "chapter:N", "beat:N" or seconds`;
  const n = Number(m[2]);
  const hit = m[1] === "chapter" ? shape.chapters?.find((c) => c.n === n) : shape.beats?.[n - 1];
  if (!hit)
    return `cue at "${at}": the timeline has no ${m[1]} ${n} (declare ${m[1]}s on window.__viz.timeline)`;
  return { t: hit.t0, slot: hit.dur };
}

/** [word, start, end] seconds into the clip — lets a page point at a thing while it is said. */
export type Word = [string, number, number];
const wordsFile = (clip: string): string => clip.replace(/\.(?:mp3|wav)$/u, ".words.json");

async function speakKokoro(text: string, voice: string, speed: number, out: string): Promise<void> {
  const body = { model: "kokoro", input: text, voice, speed, response_format: "mp3" };
  const post = async (route: string, extra: object): Promise<Response> => {
    const res = await fetch(`${KOKORO}${route}`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ ...body, ...extra }),
    });
    return res;
  };
  let audio: Uint8Array,
    words: Word[] | null = null;
  try {
    // Word timestamps come from Kokoro-FastAPI's captioned endpoint; a Kokoro without it still speaks.
    let res = await post("/dev/captioned_speech", { stream: false, return_timestamps: true });
    if (res.ok) {
      const j: unknown = await res.json();
      const b64 = field(j, "audio");
      if (!isString(b64)) throw new Error("Kokoro TTS answered without audio");
      audio = Buffer.from(b64, "base64");
      const stamps = field(j, "timestamps");
      words = (Array.isArray(stamps) ? stamps : [])
        .filter((w: unknown) => isString(field(w, "word")) && hasNums(w, "start_time", "end_time"))
        .map((w: unknown): Word => [
          String(field(w, "word")),
          Math.max(0, +Number(field(w, "start_time")).toFixed(3)),
          +Number(field(w, "end_time")).toFixed(3),
        ]);
    } else {
      res = await post("/v1/audio/speech", {});
      if (!res.ok)
        throw new Error(`Kokoro TTS answered ${res.status}: ${(await res.text()).slice(0, 200)}`);
      audio = new Uint8Array(await res.arrayBuffer());
    }
  } catch (e) {
    if (e instanceof Error && e.message.startsWith("Kokoro TTS answered")) throw e;
    throw new Error(
      `Kokoro TTS is not reachable at ${KOKORO} — start the Kokoro service (voicemode manages it), or point VIZ_KOKORO_URL at where it runs`,
      { cause: e },
    );
  }
  // 48kbps mono: speech doesn't need Kokoro's default bitrate, and publish inlines these.
  const ff = Bun.spawn(
    ["ffmpeg", "-y", "-loglevel", "error", "-i", "-", "-ac", "1", "-b:a", "48k", out],
    { stdin: audio },
  );
  if ((await ff.exited) !== 0) throw new Error(`ffmpeg could not re-encode the TTS clip → ${out}`);
  if (words) writeFileSync(wordsFile(out), JSON.stringify(words));
}

/**
 * A Qwen3 voice clone through mlx-audio's own server (`POST /v1/audio/speech`). A server that is
 * already listening at the profile's `url` is used and left running; otherwise one is started
 * with the profile's `python` for this render and stopped after it, so no model stays in memory.
 */
async function speakQwen(
  profile: VoiceProfile,
  clips: { text: string; out: string; speed: number }[],
): Promise<void> {
  if (!profile.referenceWav || !existsSync(profile.referenceWav) || !profile.transcript)
    throw new Error(
      `voice "${profile.id}" needs an existing referenceWav and transcript in VIZ_TTS_CONFIG`,
    );
  const base = profile.url ?? "http://127.0.0.1:8890";
  const up = async (): Promise<boolean> => {
    try {
      return (await fetch(`${base}/openapi.json`)).ok;
    } catch {
      return false;
    }
  };
  let server: ReturnType<typeof Bun.spawn> | undefined;
  if (!(await up())) {
    const log = path.join(os.tmpdir(), "viz-mlx-audio-server.log");
    const { hostname, port } = new URL(base);
    server = Bun.spawn(
      [profile.python ?? "python3", "-m", "mlx_audio.server", "--host", hostname, "--port", port],
      { stdout: Bun.file(log), stderr: Bun.file(log) },
    );
    // oxlint-disable-next-line no-await-in-loop -- polls the server until it answers or the deadline passes
    for (const deadline = Date.now() + 90_000; !(await up()); await Bun.sleep(500)) {
      if (server.exitCode !== null || Date.now() > deadline)
        throw new Error(
          `mlx-audio server for voice "${profile.id}" did not start (needs \`mlx-audio[server]\` in that python) — see ${log}`,
        );
    }
  }
  try {
    for (const c of clips) {
      // oxlint-disable-next-line no-await-in-loop -- clips go to the one local model server a clip at a time
      const res = await fetch(`${base}/v1/audio/speech`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          model: profile.model ?? "mlx-community/Qwen3-TTS-12Hz-1.7B-Base-8bit",
          input: c.text,
          ref_audio: profile.referenceWav,
          ref_text: profile.transcript,
          speed: c.speed,
          temperature: 0,
          lang_code: "English",
          max_tokens: 512,
          response_format: "wav",
        }),
      });
      if (!res.ok)
        throw new Error(
          // oxlint-disable-next-line no-await-in-loop -- same sequential clip loop
          `Qwen3 TTS answered ${res.status} for voice "${profile.id}": ${(await res.text()).slice(0, 200)}`,
        );
      // Buffer first: Bun 1.3.11's Bun.write(path, res) never resolves on this slow chunked body.
      // oxlint-disable-next-line no-await-in-loop -- same sequential clip loop
      await Bun.write(c.out, await res.arrayBuffer());
      if (Bun.file(c.out).size < 1000) throw new Error(`Qwen3 produced no audio for ${c.out}`);
    }
  } finally {
    server?.kill();
  }
}

/**
 * Compile the script against the timeline: synthesize missing clips, measure every clip,
 * write .tts/manifest.json, and say what doesn't fit. Warnings, not failures — the agent
 * decides whether to reword, speed up, or lengthen the beat.
 */
// oxlint-disable-next-line complexity -- one pass over voices x cues that shares its warnings; splitting it is a rewrite
export async function compile(vizDir: string, n: Narration, shape: Shape): Promise<Plan> {
  const warnings: string[] = [];
  const ttsDir = path.join(vizDir, TTS_DIR);
  mkdirSync(ttsDir, { recursive: true });
  // Build output ignores itself, so it stays out of git in whichever repo the viz lives in.
  writeFileSync(path.join(ttsDir, ".gitignore"), "*\n");

  const config = voiceConfig();
  const choices: VoiceChoice[] = n.voices?.length
    ? n.voices
    : config.defaults.map((id) => ({ id }));
  const selected = choices.length > 0 ? choices : [{ id: "kokoro" }];
  const profiles = new Map(config.profiles.map((p) => [p.id, p]));
  const resolved: VoiceProfile[] = [];
  for (const choice of selected) {
    const base: VoiceProfile | undefined =
      profiles.get(choice.id) ??
      (choice.id === "kokoro" ? { id: "kokoro", engine: "kokoro", label: "Kokoro" } : undefined);
    if (!base)
      throw new Error(
        `voice "${choice.id}" is not configured in ${process.env.VIZ_TTS_CONFIG ?? "~/.config/viz/voices.json"}`,
      );
    resolved.push({ ...base, ...choice, label: choice.label ?? base.label ?? choice.id });
  }
  if (new Set(resolved.map((v) => v.id)).size !== resolved.length)
    throw new Error("voice ids must be unique");
  const tracks: Track[] = [];
  for (const profile of resolved) {
    const cues: Placed[] = [];
    const pending: { text: string; out: string; speed: number }[] = [];
    const meta: { cue: Cue; t: number; slot: number; src: string }[] = [];
    const referenceHash =
      profile.engine === "qwen3" && profile.referenceWav && existsSync(profile.referenceWav)
        ? createHash("sha256")
            .update(readFileSync(profile.referenceWav))
            .update(profile.transcript ?? "")
            .digest("hex")
        : "";
    for (const [i, cue] of n.cues.entries()) {
      const where = place(cue.at, shape);
      if (typeof where === "string") {
        if (profile === resolved[0]) warnings.push(where);
        continue;
      }
      const label = `cue ${i + 1} (${cue.at})`;
      let src: string;
      if (cue.say) {
        const voice =
          profile.engine === "kokoro"
            ? (profile.voice ?? cue.voice ?? n.voice ?? "af_heart")
            : profile.id;
        const speed = cue.speed ?? profile.speed ?? n.speed ?? 1;
        const ext = profile.engine === "qwen3" ? "wav" : "mp3";
        const key =
          profile.engine === "qwen3"
            ? [cue.say, profile.id, voice, speed, profile.model, referenceHash]
            : [cue.say, voice, speed];
        const hash = createHash("sha256").update(JSON.stringify(key)).digest("hex").slice(0, 16);
        src = `${TTS_DIR}/${hash}.${ext}`;
        if (!existsSync(path.join(vizDir, src))) {
          // oxlint-disable-next-line max-depth -- synthesis runs one clip at a time (the TTS service is local and single-GPU)
          if (profile.engine === "kokoro")
            // oxlint-disable-next-line no-await-in-loop -- synthesis runs one clip at a time (the TTS service is local and single-GPU)
            await speakKokoro(cue.say, voice, speed, path.join(vizDir, src));
          else pending.push({ text: cue.say, out: path.join(vizDir, src), speed });
        }
      } else if (cue.audio) {
        const abs = insideViz(vizDir, cue.audio);
        if (!abs)
          throw new Error(
            `${label}: "${cue.audio}" is outside the viz folder — cue files must live in it (audio/)`,
          );
        if (!existsSync(abs)) throw new Error(`${label}: no such file ${abs}`);
        src = path.relative(vizDir, abs).split(path.sep).join("/");
      } else {
        if (profile === resolved[0]) warnings.push(`${label}: has neither "say" nor "audio"`);
        continue;
      }
      meta.push({ cue, t: where.t, slot: where.slot, src });
    }
    // oxlint-disable-next-line no-await-in-loop -- one voice's model server at a time, so only one model is in memory
    if (pending.length > 0) await speakQwen(profile, pending);
    for (const { cue, t, slot, src } of meta) {
      // oxlint-disable-next-line no-await-in-loop -- cheap ffprobe calls kept in cue order
      const dur = await probeDuration(path.join(vizDir, src));
      if (cue.say && dur > slot + 0.05)
        warnings.push(
          `${profile.label}: cue (${cue.at}) runs ${dur.toFixed(2)}s but it has ${slot.toFixed(2)}s — needs +${(dur - slot).toFixed(2)}s`,
        );
      const wf = wordsFile(path.join(vizDir, src));
      const parsedWords: unknown =
        cue.say && existsSync(wf) ? JSON.parse(readFileSync(wf, "utf8")) : undefined;
      const words = Array.isArray(parsedWords) ? parsedWords.filter(isWord) : undefined;
      cues.push({
        at: cue.at,
        t,
        dur,
        src,
        gain: cue.gain ?? 0,
        ...(cue.say !== undefined && { text: cue.say }),
        ...(cue.caption !== undefined && { caption: cue.caption }),
        ...(words && { words }),
      });
    }
    tracks.push({ id: profile.id, label: profile.label!, cues });
  }
  const slots = new Map<string, number>();
  for (const c of tracks.flatMap((t) => t.cues))
    if (c.text) slots.set(String(c.at), Math.max(slots.get(String(c.at)) ?? 0, c.dur));
  for (const track of tracks)
    for (const c of track.cues) {
      const duration = slots.get(String(c.at));
      if (duration !== undefined) c.slotDur = duration;
    }
  const cues = tracks[0]!.cues;

  // Two voices at once is a script bug; music and effects may overlap anything.
  const said = cues.filter((c) => c.text).toSorted((a, b) => a.t - b.t);
  for (let i = 1; i < said.length; i++) {
    const prev = said[i - 1]!;
    const cur = said[i]!;
    const end = prev.t + (prev.slotDur ?? prev.dur);
    if (cur.t < end - 0.05) {
      warnings.push(
        `narration overlaps: "${prev.text!.slice(0, 40)}…" (${prev.t.toFixed(2)}s–${end.toFixed(2)}s) still speaking when "${cur.text!.slice(0, 40)}…" starts at ${cur.t.toFixed(2)}s`,
      );
    }
  }

  // Warnings ride along so the page can repeat them in the browser console.
  writeFileSync(
    path.join(ttsDir, "manifest.json"),
    JSON.stringify({ cues, tracks, warnings }, null, 2) + "\n",
  );
  return { cues, tracks, warnings };
}

type Caption = { start: number; end: number; text: string };

async function transcribe(file: string, offset: number, tmp: string): Promise<Caption[]> {
  const p = Bun.spawn(
    [
      "mlx_whisper",
      file,
      "--model",
      "mlx-community/whisper-large-v3-turbo",
      "-f",
      "json",
      "-o",
      tmp,
      "--verbose",
      "False",
    ],
    { stdout: "ignore", stderr: "inherit" },
  );
  if ((await p.exited) !== 0)
    throw new Error(`mlx_whisper failed on ${file} (a cue with "caption": true needs it on PATH)`);
  const json: unknown = JSON.parse(
    readFileSync(path.join(tmp, path.basename(file).replace(/\.[^.]+$/u, "") + ".json"), "utf8"),
  );
  const segments = field(json, "segments");
  if (!Array.isArray(segments)) throw new Error(`mlx_whisper wrote no segments for ${file}`);
  return segments
    .filter(isCaption)
    .map((s) => ({ start: s.start + offset, end: s.end + offset, text: s.text.trim() }));
}

const stamp = (s: number, sep: string): string => {
  const ms = Math.round(s * 1000);
  const p = (n: number, w = 2) => String(n).padStart(w, "0");
  return `${p(Math.floor(ms / 3_600_000))}:${p(Math.floor(ms / 60_000) % 60)}:${p(Math.floor(ms / 1000) % 60)}${sep}${p(ms % 1000, 3)}`;
};

export async function captionsFor(vizDir: string, plan: Plan, tmp: string): Promise<Caption[]> {
  const out: Caption[] = plan.cues
    .filter((c) => c.text)
    .map((c) => ({ start: c.t, end: c.t + c.dur, text: c.text! }));
  for (const c of plan.cues.filter((k) => k.caption && !k.text))
    // oxlint-disable-next-line no-await-in-loop -- whisper is heavy: one clip at a time
    out.push(...(await transcribe(path.join(vizDir, c.src), c.t, tmp)));
  return out.toSorted((a, b) => a.start - b.start);
}

export const toVtt = (cs: Caption[]): string =>
  "WEBVTT\n\n" +
  cs.map((c) => `${stamp(c.start, ".")} --> ${stamp(c.end, ".")}\n${c.text}\n`).join("\n");
const toSrt = (cs: Caption[]) =>
  cs
    .map((c, i) => `${i + 1}\n${stamp(c.start, ",")} --> ${stamp(c.end, ",")}\n${c.text}\n`)
    .join("\n");

/**
 * video + placed cues + captions → out. Audio is each cue delayed to its start and mixed
 * at its gain (no ducking — set music quieter yourself). Captions ride as a soft subtitle
 * track (players toggle them) and a sidecar .vtt; they are never burned into the picture.
 */
export async function mux(opts: {
  vizDir: string;
  video: string;
  plan: Plan;
  captions: Caption[];
  total: number;
  out: string;
  tmp: string;
}): Promise<void> {
  // The video ends at total; an overrunning line is already a warning, its caption just stops.
  const o = {
    ...opts,
    captions: opts.captions
      .filter((c) => c.start < opts.total)
      .map((c) => ({ start: c.start, end: Math.min(c.end, opts.total), text: c.text })),
  };
  const args = ["-y", "-loglevel", "error", "-i", o.video];
  for (const track of o.plan.tracks)
    for (const c of track.cues) args.push("-i", path.join(o.vizDir, c.src));
  const srt = path.join(o.tmp, "captions.srt");
  if (o.captions.length > 0) {
    writeFileSync(srt, toSrt(o.captions));
    args.push("-i", srt);
  }
  const chains: string[] = [];
  let input = 1;
  for (const [ti, track] of o.plan.tracks.entries()) {
    const labels: string[] = [];
    for (const [ci, c] of track.cues.entries()) {
      const label = `a${ti}_${ci}`;
      chains.push(
        `[${input++}:a]adelay=delays=${Math.round(c.t * 1000)}:all=1,volume=${c.gain}dB[${label}]`,
      );
      labels.push(`[${label}]`);
    }
    chains.push(
      `${labels.join("")}amix=inputs=${labels.length}:normalize=0:duration=longest[mix${ti}]`,
    );
  }
  args.push("-filter_complex", chains.join(";"), "-map", "0:v");
  for (const [i] of o.plan.tracks.entries()) args.push("-map", `[mix${i}]`);
  if (o.captions.length > 0)
    args.push("-map", `${input}:s`, "-c:s", "mov_text", "-metadata:s:s:0", "language=eng");
  args.push(
    "-c:v",
    "copy",
    "-c:a",
    "aac",
    "-b:a",
    "128k",
    "-t",
    o.total.toFixed(3),
    "-movflags",
    "+faststart",
  );
  o.plan.tracks.forEach((t, i) => {
    args.push(
      `-metadata:s:a:${i}`,
      `title=${t.label}`,
      `-disposition:a:${i}`,
      i === 0 ? "default" : "0",
    );
  });
  args.push(o.out);
  const p = Bun.spawn(["ffmpeg", ...args], { stderr: "inherit" });
  if ((await p.exited) !== 0) throw new Error(`ffmpeg could not mux narration → ${o.out}`);
  if (o.captions.length > 0)
    writeFileSync(o.out.replace(/\.[^.]+$/u, "") + ".vtt", toVtt(o.captions));
}
