// lib/render/narration.ts — narration.json → timed audio clips, warnings, and a muxed mp4.
//
// The script lives in the viz (narration.json + audio/), so it is content: committed,
// edited by the agent. What it compiles to — Kokoro clips and .tts/manifest.json — is build
// output: gitignored, regenerated by hash, bundled only by publish. The browser (kit
// narrate()) and the render read the same manifest, so what you hear while stepping the
// page is what ends up in the video.
//
// Kokoro only (a decision, not an oversight). VIZ_KOKORO_URL moves it, it doesn't swap it.

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const KOKORO = process.env.VIZ_KOKORO_URL ?? "http://127.0.0.1:8880";
export const TTS_DIR = ".tts";
export const NARRATION_FILE = "narration.json";

export type Cue = {
  /** "chapter:N" (a chapter's n), "beat:N" (1-based position in beats[]), or seconds. */
  at: string | number;
  say?: string;
  /** A file under the viz dir, e.g. "audio/whoosh.mp3". */
  audio?: string;
  voice?: string;
  speed?: number;
  /** dB, e.g. -18 to sit music under speech. */
  gain?: number;
  /** Transcribe this audio file (mlx_whisper) into captions — for a real voiceover, not music. */
  caption?: boolean;
};
export type Narration = { voice?: string; speed?: number; cues: Cue[] };
export type Shape = { total: number; chapters?: { n: number; t0: number; dur: number }[]; beats?: { t0: number; dur: number }[] };

/** One cue, placed on the timeline. `src` is relative to the viz dir — the manifest's URL. */
export type Placed = { t: number; dur: number; src: string; gain: number; text?: string; caption?: boolean; words?: Word[] };
export type Plan = { cues: Placed[]; warnings: string[] };

export function readNarration(vizDir: string): Narration | null {
  const f = path.join(vizDir, NARRATION_FILE);
  if (!existsSync(f)) return null;
  const n = JSON.parse(readFileSync(f, "utf8")) as Narration;
  if (!Array.isArray(n.cues)) throw new Error(`${f}: "cues" must be an array`);
  return n;
}

export async function probeDuration(file: string): Promise<number> {
  const p = Bun.spawn(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", file], { stdout: "pipe" });
  const d = Number((await new Response(p.stdout).text()).trim());
  if (!(d > 0)) throw new Error(`could not read the duration of ${file}`);
  return d;
}

/** Where a cue starts, and how long it has before the thing it is anchored to ends. */
/** A cue's file, resolved — null if it points outside the viz (publish would inline it). */
export function insideViz(vizDir: string, rel: string): string | null {
  const abs = path.resolve(vizDir, rel);
  const r = path.relative(vizDir, abs);
  return r && !r.startsWith("..") && !path.isAbsolute(r) ? abs : null;
}

function place(at: Cue["at"], shape: Shape): { t: number; slot: number } | string {
  if (typeof at === "number") {
    if (!(at >= 0 && at < shape.total)) return `cue at ${at}: outside the film (0–${shape.total}s)`;
    return { t: at, slot: shape.total - at };
  }
  const m = /^(chapter|beat):(\d+)$/.exec(at);
  if (!m) return `cue at "${at}": expected "chapter:N", "beat:N" or seconds`;
  const n = Number(m[2]);
  const hit = m[1] === "chapter" ? shape.chapters?.find((c) => c.n === n) : shape.beats?.[n - 1];
  if (!hit) return `cue at "${at}": the timeline has no ${m[1]} ${n} (declare ${m[1]}s on window.__viz.timeline)`;
  return { t: hit.t0, slot: hit.dur };
}

/** [word, start, end] seconds into the clip — lets a page point at a thing while it is said. */
export type Word = [string, number, number];
const wordsFile = (clip: string) => clip.replace(/\.mp3$/, ".words.json");

async function speak(text: string, voice: string, speed: number, out: string): Promise<void> {
  const body = { model: "kokoro", input: text, voice, speed, response_format: "mp3" };
  const post = (route: string, extra: object) => fetch(`${KOKORO}${route}`, {
    method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...body, ...extra }),
  });
  let audio: Uint8Array, words: Word[] | null = null;
  try {
    // Word timestamps come from Kokoro-FastAPI's captioned endpoint; a Kokoro without it still speaks.
    let res = await post("/dev/captioned_speech", { stream: false, return_timestamps: true });
    if (res.ok) {
      const j = (await res.json()) as { audio: string; timestamps?: { word: string; start_time: number; end_time: number }[] };
      audio = Buffer.from(j.audio, "base64");
      words = (j.timestamps ?? []).map((w) => [w.word, Math.max(0, +w.start_time.toFixed(3)), +w.end_time.toFixed(3)]);
    } else {
      res = await post("/v1/audio/speech", {});
      if (!res.ok) throw new Error(`Kokoro TTS answered ${res.status}: ${(await res.text()).slice(0, 200)}`);
      audio = new Uint8Array(await res.arrayBuffer());
    }
  } catch (e) {
    if ((e as Error).message.startsWith("Kokoro TTS answered")) throw e;
    throw new Error(`Kokoro TTS is not reachable at ${KOKORO} — start the Kokoro service (voicemode manages it), or point VIZ_KOKORO_URL at where it runs`);
  }
  // 48kbps mono: speech doesn't need Kokoro's default bitrate, and publish inlines these.
  const ff = Bun.spawn(["ffmpeg", "-y", "-loglevel", "error", "-i", "-", "-ac", "1", "-b:a", "48k", out], { stdin: audio });
  if ((await ff.exited) !== 0) throw new Error(`ffmpeg could not re-encode the TTS clip → ${out}`);
  if (words) writeFileSync(wordsFile(out), JSON.stringify(words));
}

/**
 * Compile the script against the timeline: synthesize missing clips, measure every clip,
 * write .tts/manifest.json, and say what doesn't fit. Warnings, not failures — the agent
 * decides whether to reword, speed up, or lengthen the beat.
 */
export async function compile(vizDir: string, n: Narration, shape: Shape): Promise<Plan> {
  const warnings: string[] = [];
  const cues: Placed[] = [];
  const ttsDir = path.join(vizDir, TTS_DIR);
  mkdirSync(ttsDir, { recursive: true });
  // Build output ignores itself, so it stays out of git in whichever repo the viz lives in.
  writeFileSync(path.join(ttsDir, ".gitignore"), "*\n");

  for (const [i, cue] of n.cues.entries()) {
    const where = place(cue.at, shape);
    if (typeof where === "string") { warnings.push(where); continue; }
    const label = `cue ${i + 1} (${cue.at})`;
    let src: string;
    if (cue.say) {
      const voice = cue.voice ?? n.voice ?? "af_heart";
      const speed = cue.speed ?? n.speed ?? 1;
      const hash = createHash("sha256").update(JSON.stringify([cue.say, voice, speed])).digest("hex").slice(0, 16);
      src = `${TTS_DIR}/${hash}.mp3`;
      // A clip cached before word timings existed is regenerated once to gain them.
      if (!existsSync(path.join(vizDir, src)) || !existsSync(wordsFile(path.join(vizDir, src)))) await speak(cue.say, voice, speed, path.join(vizDir, src));
    } else if (cue.audio) {
      const abs = insideViz(vizDir, cue.audio);
      if (!abs) throw new Error(`${label}: "${cue.audio}" is outside the viz folder — cue files must live in it (audio/)`);
      if (!existsSync(abs)) throw new Error(`${label}: no such file ${abs}`);
      src = path.relative(vizDir, abs).split(path.sep).join("/");
    } else {
      warnings.push(`${label}: has neither "say" nor "audio"`);
      continue;
    }
    const dur = await probeDuration(path.join(vizDir, src));
    if (cue.say && dur > where.slot + 0.05) {
      warnings.push(`${label}: narration runs ${dur.toFixed(2)}s but it has ${where.slot.toFixed(2)}s — needs +${(dur - where.slot).toFixed(2)}s (shorten the line, raise "speed", or lengthen the ${String(cue.at).split(":")[0]})`);
    }
    const wf = wordsFile(path.join(vizDir, src));
    const words = cue.say && existsSync(wf) ? (JSON.parse(readFileSync(wf, "utf8")) as Word[]) : undefined;
    cues.push({ t: where.t, dur, src, gain: cue.gain ?? 0, text: cue.say, caption: cue.caption, words });
  }

  // Two voices at once is a script bug; music and effects may overlap anything.
  const said = cues.filter((c) => c.text).sort((a, b) => a.t - b.t);
  for (let i = 1; i < said.length; i++) {
    const prev = said[i - 1];
    if (said[i].t < prev.t + prev.dur - 0.05) {
      warnings.push(`narration overlaps: "${prev.text!.slice(0, 40)}…" (${prev.t.toFixed(2)}s–${(prev.t + prev.dur).toFixed(2)}s) still speaking when "${said[i].text!.slice(0, 40)}…" starts at ${said[i].t.toFixed(2)}s`);
    }
  }

  // Warnings ride along so the page can repeat them in the browser console.
  writeFileSync(path.join(ttsDir, "manifest.json"), JSON.stringify({ cues, warnings }, null, 2) + "\n");
  return { cues, warnings };
}

type Caption = { start: number; end: number; text: string };

async function transcribe(file: string, offset: number, tmp: string): Promise<Caption[]> {
  const p = Bun.spawn(["mlx_whisper", file, "--model", "mlx-community/whisper-large-v3-turbo", "-f", "json", "-o", tmp, "--verbose", "False"], { stdout: "ignore", stderr: "inherit" });
  if ((await p.exited) !== 0) throw new Error(`mlx_whisper failed on ${file} (a cue with "caption": true needs it on PATH)`);
  const json = JSON.parse(readFileSync(path.join(tmp, path.basename(file).replace(/\.[^.]+$/, "") + ".json"), "utf8")) as { segments: Caption[] };
  return json.segments.map((s) => ({ start: s.start + offset, end: s.end + offset, text: s.text.trim() }));
}

const stamp = (s: number, sep: string) => {
  const ms = Math.round(s * 1000);
  const p = (n: number, w = 2) => String(n).padStart(w, "0");
  return `${p(Math.floor(ms / 3_600_000))}:${p(Math.floor(ms / 60_000) % 60)}:${p(Math.floor(ms / 1000) % 60)}${sep}${p(ms % 1000, 3)}`;
};

export async function captionsFor(vizDir: string, plan: Plan, tmp: string): Promise<Caption[]> {
  const out: Caption[] = plan.cues.filter((c) => c.text).map((c) => ({ start: c.t, end: c.t + c.dur, text: c.text! }));
  for (const c of plan.cues.filter((c) => c.caption && !c.text)) out.push(...(await transcribe(path.join(vizDir, c.src), c.t, tmp)));
  return out.sort((a, b) => a.start - b.start);
}

export const toVtt = (cs: Caption[]) => "WEBVTT\n\n" + cs.map((c) => `${stamp(c.start, ".")} --> ${stamp(c.end, ".")}\n${c.text}\n`).join("\n");
const toSrt = (cs: Caption[]) => cs.map((c, i) => `${i + 1}\n${stamp(c.start, ",")} --> ${stamp(c.end, ",")}\n${c.text}\n`).join("\n");

/**
 * video + placed cues + captions → out. Audio is each cue delayed to its start and mixed
 * at its gain (no ducking — set music quieter yourself). Captions ride as a soft subtitle
 * track (players toggle them) and a sidecar .vtt; they are never burned into the picture.
 */
export async function mux(o: { vizDir: string; video: string; plan: Plan; captions: Caption[]; total: number; out: string; tmp: string }): Promise<void> {
  // The video ends at total; an overrunning line is already a warning, its caption just stops.
  o = { ...o, captions: o.captions.filter((c) => c.start < o.total).map((c) => ({ ...c, end: Math.min(c.end, o.total) })) };
  const args = ["-y", "-loglevel", "error", "-i", o.video];
  for (const c of o.plan.cues) args.push("-i", path.join(o.vizDir, c.src));
  const srt = path.join(o.tmp, "captions.srt");
  if (o.captions.length) { writeFileSync(srt, toSrt(o.captions)); args.push("-i", srt); }
  const chains = o.plan.cues.map((c, k) => `[${k + 1}:a]adelay=delays=${Math.round(c.t * 1000)}:all=1,volume=${c.gain}dB[a${k}]`);
  const mixIn = o.plan.cues.map((_, k) => `[a${k}]`).join("");
  args.push("-filter_complex", `${chains.join(";")};${mixIn}amix=inputs=${o.plan.cues.length}:normalize=0:duration=longest[mix]`);
  args.push("-map", "0:v", "-map", "[mix]");
  if (o.captions.length) args.push("-map", `${o.plan.cues.length + 1}:s`, "-c:s", "mov_text", "-metadata:s:s:0", "language=eng");
  args.push("-c:v", "copy", "-c:a", "aac", "-b:a", "128k", "-t", o.total.toFixed(3), "-movflags", "+faststart", o.out);
  const p = Bun.spawn(["ffmpeg", ...args], { stderr: "inherit" });
  if ((await p.exited) !== 0) throw new Error(`ffmpeg could not mux narration → ${o.out}`);
  if (o.captions.length) writeFileSync(o.out.replace(/\.[^.]+$/, "") + ".vtt", toVtt(o.captions));
}
